version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: guestara_db
    restart: always
    environment:
      POSTGRES_USER: guestara_user
      POSTGRES_PASSWORD: guestara_password
      POSTGRES_DB: guestara_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: